prefixes:
  "31.170.120.0/21": 22422
  "31.170.120.0/24": 20712
  "31.170.122.0/24": 20713
  "31.170.123.0/24": 20756
  "46.32.224.0/19": 20744
  "46.32.224.0/24": 20738
  "46.32.228.0/23": 20321
  "46.32.230.0/23": 20212


betterstack_webhook: "https://uptime.betterstack.com/api/v1/incoming-wsdadsa"

email_settings:
  enabled: true  # Set to false if you don't want email alerts
  sender_email: "bgp-hijack@heartinternet.uk"
  recipient_email:
    - "xxxx@gmail.com"
    - "ayyy@gmail.com"
  smtp_server: "10.93.139.45"
  smtp_port: 25
  use_authentication: false  # Set to true if authentication is required
  smtp_username:
  smtp_password:  # Leave empty if use_authentication is false
